Vagrant.configure("2") do |config|
if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
config.vm.define :servidorPXE do |servidor|
servidor.vm.box = "bento/centos-7.9"
servidor.vm.network :private_network, ip: "192.168.50.4"
servidor.vm.hostname = "servidorPXE"
end
end